export const currencyData = [
    { label: "AED", value: "AED", name: "United Arab Emirates Dirham" },
    { label: "AFN", value: "AFN", name: "Afghanistan Afghani" },
    { label: "ALL", value: "ALL", name: "Albania Lek" },
    { label: "AMD", value: "AMD", name: "Armenia Dram" },
    { label: "ANG", value: "ANG", name: "Netherlands Antilles Guilder" },
    { label: "AOA", value: "AOA", name: "Angola Kwanza" },
    { label: "ARS", value: "ARS", name: "Argentina Peso" },
    { label: "AUD", value: "AUD", name: "Australia Dollar" },
    { label: "AWG", value: "AWG", name: "Aruba Guilder" },
    { label: "AZN", value: "AZN", name: "Azerbaijan Manat" },
    { label: "BAM", value: "BAM", name: "Bosnia and Herzegovina Convertible Mark" },
    { label: "BBD", value: "BBD", name: "Barbados Dollar" },
    { label: "BDT", value: "BDT", name: "Bangladesh Taka" },
    { label: "BGN", value: "BGN", name: "Bulgaria Lev" },
    { label: "BHD", value: "BHD", name: "Bahrain Dinar" },
    { label: "BIF", value: "BIF", name: "Burundi Franc" },
    { label: "BMD", value: "BMD", name: "Bermuda Dollar" },
    { label: "BND", value: "BND", name: "Brunei Darussalam Dollar" },
    { label: "BOB", value: "BOB", name: "Bolivia Bolíviano" },
    { label: "BRL", value: "BRL", name: "Brazil Real" },
    { label: "BSD", value: "BSD", name: "Bahamas Dollar" },
    { label: "BTN", value: "BTN", name: "Bhutan Ngultrum" },
    { label: "BWP", value: "BWP", name: "Botswana Pula" },
    { label: "BYN", value: "BYN", name: "Belarus Ruble" },
    { label: "BZD", value: "BZD", name: "Belize Dollar" },
    { label: "CAD", value: "CAD", name: "Canada Dollar" },
    { label: "CDF", value: "CDF", name: "Congo/Kinshasa Franc" },
    { label: "CHF", value: "CHF", name: "Switzerland Franc" },
    { label: "CLP", value: "CLP", name: "Chile Peso" },
    { label: "CNY", value: "CNY", name: "China Yuan Renminbi" },
    { label: "COP", value: "COP", name: "Colombia Peso" },
    { label: "CRC", value: "CRC", name: "Costa Rica Colon" },
    { label: "CUC", value: "CUC", name: "Cuba Convertible Peso" },
    { label: "CUP", value: "CUP", name: "Cuba Peso" },
    { label: "CVE", value: "CVE", name: "Cape Verde Escudo" },
    { label: "CZK", value: "CZK", name: "Czech Republic Koruna" },
    { label: "DJF", value: "DJF", name: "Djibouti Franc" },
    { label: "DKK", value: "DKK", name: "Denmark Krone" },
    { label: "DOP", value: "DOP", name: "Dominican Republic Peso" },
    { label: "DZD", value: "DZD", name: "Algeria Dinar" },
    { label: "EGP", value: "EGP", name: "Egypt Pound" },
    { label: "ERN", value: "ERN", name: "Eritrea Nakfa" },
    { label: "ETB", value: "ETB", name: "Ethiopia Birr" },
    { label: "EUR", value: "EUR", name: "Euro Member Countries" },
    { label: "FJD", value: "FJD", name: "Fiji Dollar" },
    { label: "FKP", value: "FKP", name: "Falkland Islands (Malvinas) Pound" },
    { label: "GBP", value: "GBP", name: "United Kingdom Pound" },
    { label: "GEL", value: "GEL", name: "Georgia Lari" },
    { label: "GGP", value: "GGP", name: "Guernsey Pound" },
    { label: "GHS", value: "GHS", name: "Ghana Cedi" },
    { label: "GIP", value: "GIP", name: "Gibraltar Pound" },
    { label: "GMD", value: "GMD", name: "Gambia Dalasi" },
    { label: "GNF", value: "GNF", name: "Guinea Franc" },
    { label: "GTQ", value: "GTQ", name: "Guatemala Quetzal" },
    { label: "GYD", value: "GYD", name: "Guyana Dollar" },
    { label: "HKD", value: "HKD", name: "Hong Kong Dollar" },
    { label: "HNL", value: "HNL", name: "Honduras Lempira" },
    { label: "HRK", value: "HRK", name: "Croatia Kuna" },
    { label: "HTG", value: "HTG", name: "Haiti Gourde" },
    { label: "HUF", value: "HUF", name: "Hungary Forint" },
    { label: "IDR", value: "IDR", name: "Indonesia Rupiah" },
    { label: "ILS", value: "ILS", name: "Israel Shekel" },
    { label: "IMP", value: "IMP", name: "Isle of Man Pound" },
    { label: "INR", value: "INR", name: "India Rupee" },
    { label: "IQD", value: "IQD", name: "Iraq Dinar" },
    { label: "IRR", value: "IRR", name: "Iran Rial" },
    { label: "ISK", value: "ISK", name: "Iceland Krona" },
    { label: "JEP", value: "JEP", name: "Jersey Pound" },
    { label: "JMD", value: "JMD", name: "Jamaica Dollar" },
    { label: "JOD", value: "JOD", name: "Jordan Dinar" },
    { label: "JPY", value: "JPY", name: "Japan Yen" },
    { label: "KES", value: "KES", name: "Kenya Shilling" },
    { label: "KGS", value: "KGS", name: "Kyrgyzstan Som" },
    { label: "KHR", value: "KHR", name: "Cambodia Riel" },
    { label: "KMF", value: "KMF", name: "Comorian Franc" },
    { label: "KPW", value: "KPW", name: "Korea (North) Won" },
    { label: "KRW", value: "KRW", name: "Korea (South) Won" },
    { label: "KWD", value: "KWD", name: "Kuwait Dinar" },
    { label: "KYD", value: "KYD", name: "Cayman Islands Dollar" },
    { label: "KZT", value: "KZT", name: "Kazakhstan Tenge" },
    { label: "LAK", value: "LAK", name: "Laos Kip" },
    { label: "LBP", value: "LBP", name: "Lebanon Pound" },
    { label: "LKR", value: "LKR", name: "Sri Lanka Rupee" },
    { label: "LRD", value: "LRD", name: "Liberia Dollar" },
    { label: "LSL", value: "LSL", name: "Lesotho Loti" },
    { label: "LYD", value: "LYD", name: "Libya Dinar" },
    { label: "MAD", value: "MAD", name: "Morocco Dirham" },
    { label: "MDL", value: "MDL", name: "Moldova Leu" },
    { label: "MGA", value: "MGA", name: "Madagascar Ariary" },
    { label: "MKD", value: "MKD", name: "Macedonia Denar" },
    { label: "MMK", value: "MMK", name: "Myanmar (Burma) Kyat" },
    { label: "MNT", value: "MNT", name: "Mongolia Tughrik" },
    { label: "MOP", value: "MOP", name: "Macau Pataca" },
    { label: "MRU", value: "MRU", name: "Mauritania Ouguiya" },
    { label: "MUR", value: "MUR", name: "Mauritius Rupee" },
    { label: "MVR", value: "MVR", name: "Maldives (Maldive Islands) Rufiyaa" },
    { label: "MWK", value: "MWK", name: "Malawi Kwacha" },
    { label: "MXN", value: "MXN", name: "Mexico Peso" },
    { label: "MYR", value: "MYR", name: "Malaysia Ringgit" },
    { label: "MZN", value: "MZN", name: "Mozambique Metical" },
    { label: "NAD", value: "NAD", name: "Namibia Dollar" },
    { label: "NGN", value: "NGN", name: "Nigeria Naira" },
    { label: "NIO", value: "NIO", name: "Nicaragua Cordoba" },
    { label: "NOK", value: "NOK", name: "Norway Krone" },
    { label: "NPR", value: "NPR", name: "Nepal Rupee" },
    { label: "NZD", value: "NZD", name: "New Zealand Dollar" },
    { label: "OMR", value: "OMR", name: "Oman Rial" },
    { label: "PAB", value: "PAB", name: "Panama Balboa" },
    { label: "PEN", value: "PEN", name: "Peru Sol" },
    { label: "PGK", value: "PGK", name: "Papua New Guinea Kina" },
    { label: "PHP", value: "PHP", name: "Philippines Peso" },
    { label: "PKR", value: "PKR", name: "Pakistan Rupee" },
    { label: "PLN", value: "PLN", name: "Poland Zloty" },
    { label: "PYG", value: "PYG", name: "Paraguay Guarani" },
    { label: "QAR", value: "QAR", name: "Qatar Riyal" },
    { label: "RON", value: "RON", name: "Romania Leu" },
    { label: "RSD", value: "RSD", name: "Serbia Dinar" },
    { label: "RUB", value: "RUB", name: "Russia Ruble" },
    { label: "RWF", value: "RWF", name: "Rwanda Franc" },
    { label: "SAR", value: "SAR", name: "Saudi Arabia Riyal" },
    { label: "SBD", value: "SBD", name: "Solomon Islands Dollar" },
    { label: "SCR", value: "SCR", name: "Seychelles Rupee" },
    { label: "SDG", value: "SDG", name: "Sudan Pound" },
    { label: "SEK", value: "SEK", name: "Sweden Krona" },
    { label: "SGD", value: "SGD", name: "Singapore Dollar" },
    { label: "SHP", value: "SHP", name: "Saint Helena Pound" },
    { label: "SLL", value: "SLL", name: "Sierra Leone Leone" },
    { label: "SOS", value: "SOS", name: "Somalia Shilling" },
    { label: "SPL", value: "SPL", name: "Seborga Luigino" },
    { label: "SRD", value: "SRD", name: "Suriname Dollar" },
    { label: "STN", value: "STN", name: "São Tomé and Príncipe Dobra" },
    { label: "SVC", value: "SVC", name: "El Salvador Colon" },
    { label: "SYP", value: "SYP", name: "Syria Pound" },
    { label: "SZL", value: "SZL", name: "Swatini Lilangeni" },
    { label: "THB", value: "THB", name: "Thailand Baht" },
    { label: "TJS", value: "TJS", name: "Tajikistan Somoni" },
    { label: "TMT", value: "TMT", name: "Turkmenistan Manat" },
    { label: "TND", value: "TND", name: "Tunisia Dinar" },
    { label: "TOP", value: "TOP", name: "Tonga Pa'anga" },
    { label: "TRY", value: "TRY", name: "Turkey Lira" },
    { label: "TTD", value: "TTD", name: "Trinidad and Tobago Dollar" },
    { label: "TVD", value: "TVD", name: "Tuvalu Dollar" },
    { label: "TWD", value: "TWD", name: "Taiwan New Dollar" },
    { label: "TZS", value: "TZS", name: "Tanzania Shilling" },
    { label: "UAH", value: "UAH", name: "Ukraine Hryvnia" },
    { label: "UGX", value: "UGX", name: "Uganda Shilling" },
    { label: "USD", value: "USD", name: "United States Dollar" },
    { label: "UYU", value: "UYU", name: "Uruguay Peso" },
    { label: "UZS", value: "UZS", name: "Uzbekistan Som" },
    { label: "VEF", value: "VEF", name: "Venezuela Bolívar" },
    { label: "VND", value: "VND", name: "Viet Nam Dong" },
    { label: "VUV", value: "VUV", name: "Vanuatu Vatu" },
    { label: "WST", value: "WST", name: "Samoa Tala" },
    { label: "XAF", value: "XAF", name: "Communauté Financière Africaine (BEAC) CFA Franc BEAC" },
    { label: "XCD", value: "XCD", name: "East Caribbean Dollar" },
    { label: "XDR", value: "XDR", name: "International Monetary Fund (IMF) Special Drawing Rights" },
    { label: "XOF", value: "XOF", name: "Communauté Financière Africaine (BCEAO) Franc" },
    { label: "XPF", value: "XPF", name: "Comptoirs Français du Pacifique (CFP) Franc" },
    { label: "YER", value: "YER", name: "Yemen Rial" },
    { label: "ZAR", value: "ZAR", name: "South Africa Rand" },
    { label: "ZMW", value: "ZMW", name: "Zambia Kwacha" },
    { label: "ZWD", value: "ZWD", name: "Zimbabwe Dollar" }
];
